import {parseDocument,findDate,findInvoiceNumber,findQuoteValidity} from './ingestion.js';
let passed=0,failed=0;
function t(label,got,expected){if(JSON.stringify(got)===JSON.stringify(expected)){passed++;console.log('PASS',label)}else{failed++;console.error('FAIL',label,got,'expected',expected)}}
const email=`From: orders@vendor.com\nSubject: New prices September 21\n\nChicken breast 40 lb $82.50\nChicken base 1 lb $14.00\nChicken thighs 40 lb $54.00`;
const e=parseDocument(email);
t('informal email is a price list',e.documentKind,'pricelist');
t('informal email has exactly 3 products',e.rows.length,3);
t('no fictitious $21 subject price',e.rows.some(r=>r.price===21),false);
t('breast quote parsed',e.rows[0].price,82.5);
t('pack is preserved',e.rows[0].packSize,'40 lb');
t('base remains separate description',e.rows[1].description,'Chicken base 1 lb');
t('metadata not imported as product',e.rows.some(r=>/from:|subject:|invoice\s*#/i.test(r.description)),false);
const invoice=`INVOICE #8765\nDate 09/14/2026\nItem: Chicken Breast Qty: 2 Price: $82.50 Total: $165.00\nItem: Chicken Base Qty: 1 Price: $14.00 Total: $14.00\nTotal: $179.00`;
const i=parseDocument(invoice);
t('invoice classified as invoice',i.documentKind,'invoice');
t('invoice has exactly 2 products',i.rows.length,2);
t('invoice number not fictitious price',i.rows.some(r=>r.price===765),false);
t('invoice line total preserved',i.rows[0].amount,165);
t('invoice unit price preserved',i.rows[0].price,82.5);
t('invoice date detected',findDate(invoice),'2026-09-14');
t('invoice number detected',findInvoiceNumber(invoice),'8765');
const faulty=parseDocument('INVOICE #8766\nItem: Chicken Breast Qty: 2 Price: $82.50 Total: $175.00');
t('arithmetic discrepancy flagged',faulty.rows[0].issues.length>0,true);
t('no invalid Feb 31 date',findDate('Date: 02/31/2026'),null);
t('vendor valid-through date',findQuoteValidity('New prices\nValid through September 27, 2026'),'2026-09-27');
const unpriced=parseDocument('From: supplier@example.com\nSubject: Price list\nCHICKEN BREAST 40 LB 82');
t('unlabeled integer cannot be assumed price',unpriced.rows.length,0);
const expensive=parseDocument('From: supplier@example.com\nSubject: New prices\nIndustrial assembly 1000.00');
t('four digit unformatted price retained',expensive.rows[0]?.price,1000);
console.log(`${passed} passed, ${failed} failed`);process.exit(failed?1:0);
